name: Knight-Lite-Active

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: knight-lite-run
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows GITHUB_TOKEN to save your session

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      
      - name: Run Bot
        run: timeout 340m node index.js || echo "Restarting cycle..."
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}

      - name: Auto-Save Session
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Sync Session Data [Knight-Lite]"
          file_pattern: 'session/*.json'
        env:
          GITHUB_TOKEN: ${{ secrets.WAZIMU }}
